Issue 1065
esnet/iperf pull request #1070
Opened 2020-11-09 11:07 UTC by ralcini

* feat: Allow to configure a custom value for time drift between client/server for authentication

The use case is to support scenarios where it's not possible to enforce sync between client and server times.

2020-11-10 02:10 UTC, bmah888 requested changes
Thanks for the PR!  I did some quick functional testing, looks good.

The one change I'd like to see is to use the term "clock skew" instead of "clock drift". Clock drift is a difference in the rate between two clocks. Clock skew is a difference in the absolute value between two clocks, and that is the check that the authorization code does here. I think a global substitution of "drift" -> "skew" would take care of this. Would it be possible to do that? Quite happy to merge after that change. (Also it's great that you did all the documentation updates in this PR as well, thank you!)

2020-11-10 10:18 UTC, ralcini commented
Hi @bmah888 , thank you for your review. I've just committed the proposed change

2020-11-11 16:29 UTC, bmah888 commented
Thanks @ralcini! Looks good so far, I'll do one more round of tests on this and then merge. Hopefully by the end of this week.

2020-11-12 01:27 UTC, bmah888 approved these changes
Looks great thanks again!

2020-11-12 01:27 UTC, merged

2020-11-26 23:30 UTC, ralcini commented
@bmah888 thank you for the quick merge approval!