Test bandwidth (--bitrate) added to JSON output
esnet/iperf pull request #1168
Opened 2021-06-15 22:22 UTC by TheRealDJ

Fixes https://github.com/esnet/iperf/issues/1167 ... Bandwidth (--bitrate) parameter missing from JSON output.

2021-06-21 15:10 UTC, ejv commented
Thanks for the contribution.

During TCP tests and when specified by the user, the desired target bitrate is recorded in the JSON dict under the key `target_bitrate` (not nested in `test_start`). In the spirit of consistency, would it not be preferable to standardize around this and add a `target_bitrate` for UDP tests, as well?

Also, I'm not supportive of calling the new key you've added "bandwidth". Bandwidth typically refers to a data link's overall available capacity: `target_bitrate` seems more precise.

2021-06-21 17:48 UTC, TheRealDJ commented
The command line option used to be `--bandwidth` (which still works) and is now `--bitrate`. I'm fine with `target_bitrate` but it should be in under `test_start`, and should always be listed in the JSON. PR updated with `target_bitrate` key name.

2021-06-21 19:10 UTC, TheRealDJ commented
I did not remove existing `target_bitrate` (not nested) key as to not break any existing implementations.

2021-06-28 22:30 UTC, bmah888 commented
Hey @TheRealDJ thanks for the PR! First, I'm trying to understand what the bug is here. Is the problem that `target_bitrate` is included in `start` for TCP tests, but it's not included anywhere for UDP tests?  If so, that's consistent with what I'm seeing and I agree that's a bug.

Around line 896 of `src/iperf_api.c` is the following code:
```
    if (test->json_output) {
	cJSON_AddStringToObject(test->json_start, "cookie", test->cookie);
        if (test->protocol->id == SOCK_STREAM) {
	    if (test->settings->mss)
		cJSON_AddNumberToObject(test->json_start, "tcp_mss", test->settings->mss);
	    else {
		cJSON_AddNumberToObject(test->json_start, "tcp_mss_default", test->ctrl_sck_mss);
	    }
        if (test->settings->rate)
            cJSON_AddNumberToObject(test->json_start, "target_bitrate", test->settings->rate);
        }
```
The main bug here is that the `if (test->settings->rate)` conditional is actually included inside the `if (test->protocol-> == SOCK_STREAM)` conditional. So we only put `target_bitrate` into the JSON if we're doing TCP. (As an aside I'm not sure what happens in the case of SCTP.)

A second bug is that we should probably just print `target_bitrate` even if it's `0`.

So without having thought about this very much, I'm inclined to solve the problem by moving the closing brace on the last line of the code snippet up two lines, getting rid of the `if (test->settings->rate)` line, and then fixing up the indentation on the `target_bitrate` line. I think that will fix the problem.

The PR that you submitted puts `target_bitrate` into the `test_start` structure. Is there a particular reason it has to be there? Or would it be OK to have `target_bitrate` in`start`?

2021-06-29 20:10 UTC, TheRealDJ commented
I put it in `test_start` because that is where all of the rest of the test parameters are listed. To be honest, I didn't even notice it listed in the json root until pointed out by @ejv ... I was looking in `test_start`. As to not break anyone's existing implimentation, I didn't move the root `target_bitrate`, I only added to the `test_start` section.

2021-06-30 05:55 UTC, bmah888 commented
> I put it in `test_start` because that is where all of the rest of the test parameters are listed. To be honest, I didn't even notice it listed in `start` until pointed out by @ejv ... I was looking in `test_start`. As to not break anyone's existing implementation, I didn't move the `start`.`target_bitrate`, I only added to the `test_start` section. I guess it is ok to have it in start, but test_start seems like a better place (just my opinion).
> 
> I agree on the other 2 points ... Always list the value in the JSON, and include for all protocols.

Hmmm...I think I see your point, at least I'm about 80% there.

2021-06-30 15:04 UTC, bmah888 requested changes
OK. If you can put a (int64_t) cast before `test->settings->rate` in the line you changed, we'll call this good to go. I might want to do a follow-up commit to fix the `target_bitrate` in the `start` structure as I described in comments, just to keep everything consistent. Thanks!

2021-06-30 15:41 UTC, bmah888 approved these changes
Looks good, thanks!

2021-06-30 15:45 UTC, merged