Fix logfile file descriptor server leak
esnet/iperf pull request #1369
Opened 2022-08-03 15:23 UTC by crazyfermions

* Version of iperf3 (or development branch, such as `master` or
  `3.1-STABLE`) to which this pull request applies: master

* Issues fixed (if any): #1360 

* Brief description of code changes (suitable for use as a commit message):

```
Fix logfile fd leak in server

Makes server clean-up more robust, prevent fd leak and closing reopened fds by improving handing of fds (ensure -1 is set to an fd if it is closed to prevent closing an unrelated file if fd is reused). 
```

2022-08-09 14:45 UTC, bmah888 requested changes
A couple places where we need curly braces to make the conditionals work right when setting CPU affinity or doing JSON output.

2022-08-09 14:50 UTC, bmah888 commented
Hey @crazyfermions I think I like the basis of your PR better than mine (#1368) because you blow away the variables that keep track of sockets after the sockets get closed. That's better than what I was doing. There are a couple of minor fix-ups needed, but I think we should try to get #1369 into shape and use that to fix bug #1360. I haven't had a chance to run-test this code yet.

2022-08-09 14:52 UTC, bmah888 commented
Oh and I forgot to say thanks for submitting this PR!

2022-08-22 08:19 UTC, crazyfermions commented on src/iperf_server_api.c
>  	    return -2;
Of course, you are absolutely right.

2022-08-22 08:22 UTC, crazyfermions commented
I fixed the embarrassing bug you caught. Do you plan on stashing this pull request? Otherwise, I thing it would make sense to rebase it and merge the fix with the other commit to reduce noise.

2022-08-22 22:55 UTC, bmah888 commented
Thanks for the changes. Lemme test / play around with your code a bit. If all goes well, I'm thinking to maybe squash and merge all of the changes in this PR as a single commit onto `master`. (In theory no further action on your part would be needed.)

2022-08-22 22:57 UTC, bmah888 approved these changes

2022-08-23 20:19 UTC, merged

2022-08-23 20:19 UTC, bmah888 commented
Thanks again for the fix!