Add Time Flag For The Iperf Server Process
esnet/iperf pull request #1684
Opened 2024-04-19 00:16 UTC by manedurphy

_PLEASE NOTE the following text from the iperf3 license.  Submitting a
pull request to the iperf3 repository constitutes "[making]
Enhancements available...publicly":_

```
You are under no obligation whatsoever to provide any bug fixes, patches, or
upgrades to the features, functionality or performance of the source code
("Enhancements") to anyone; however, if you choose to make your Enhancements
available either publicly, or directly to Lawrence Berkeley National
Laboratory, without imposing a separate written license agreement for such
Enhancements, then you hereby grant the following license: a non-exclusive,
royalty-free perpetual license to install, use, modify, prepare derivative
works, incorporate into other computer software, distribute, and sublicense
such enhancements or derivative works thereof, in binary and source code form.
```

_The complete iperf3 license is available in the `LICENSE` file in the
top directory of the iperf3 source tree._

* Version of iperf3 (or development branch, such as `master` or
  `3.1-STABLE`) to which this pull request applies: master

* Issues fixed (if any): #354, #615 

* Brief description of code changes (suitable for use as a commit message):
These changes add the functionality as requested by the linked issues. Specifically, this functionality allows the server to determine the maximum duration of an `iperf` measurement. The implementation is similar to the `--server-bitrate-limit` flag, where the measurement is forcibly stopped when an interval has exceeded the server's configured bitrate. In this case, the measurement is forcibly stopped when the duration exceeds the server's configured time, which is the value of `--server-time`.

### Example

From the dropdowns below, we can see that the server has enforced a measurement time of `3` seconds. The client attempts to run the measurement for `4` seconds. When the 3rd second is exceeded, the socket is forcibly closed.

<details>

<summary>server</summary>

```txt
./src/iperf3 -s --server-time 3
-----------------------------------------------------------
Server listening on 5201 (test #1)
-----------------------------------------------------------
Accepted connection from 127.0.0.1, port 44938
[  6] local 127.0.0.1 port 5201 connected to 127.0.0.1 port 44946
[ ID] Interval           Transfer     Bitrate
[  6]   0.00-1.00   sec  3.08 GBytes  26.5 Gbits/sec                  (omitted)
[  6]   1.00-2.00   sec  3.35 GBytes  28.8 Gbits/sec                  (omitted)
[  6]   2.00-3.00   sec  3.18 GBytes  27.3 Gbits/sec                  (omitted)
[  6]   0.00-1.00   sec  3.20 GBytes  27.5 Gbits/sec
[  6]   1.00-2.00   sec  3.34 GBytes  28.7 Gbits/sec
iperf3: error - select failed: Bad file descriptor
-----------------------------------------------------------
Server listening on 5201 (test #2)
-----------------------------------------------------------
```

</details>

<details>

<summary>client</summary>

```txt
./src/iperf3 --client 127.0.0.1 --port 5201 -t 4 --omit 3
Connecting to host 127.0.0.1, port 5201
[  5] local 127.0.0.1 port 44946 connected to 127.0.0.1 port 5201
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[  5]   0.00-1.00   sec  3.08 GBytes  26.5 Gbits/sec    0   1.06 MBytes       (omitted)
[  5]   1.00-2.00   sec  3.35 GBytes  28.8 Gbits/sec    0   1.06 MBytes       (omitted)
[  5]   2.00-3.00   sec  3.15 GBytes  27.1 Gbits/sec    0   1.06 MBytes       (omitted)
[  5]   0.00-1.00   sec  3.20 GBytes  27.5 Gbits/sec    0   1.12 MBytes
[  5]   1.00-2.00   sec  3.34 GBytes  28.7 Gbits/sec    0   1.25 MBytes
[  5]   1.00-2.00   sec  3.34 GBytes  28.7 Gbits/sec    0   1.25 MBytes
iperf3: error - control socket has closed unexpectedly
```

</details>

<details>

<summary>client_json</summary>

```json
{
        "start":        {
                "connected":    [{
                                "socket":       5,
                                "local_host":   "127.0.0.1",
                                "local_port":   53314,
                                "remote_host":  "127.0.0.1",
                                "remote_port":  5201
                        }],
                "version":      "iperf 3.16+",
                "system_info":  "Linux windows-nexus 5.15.146.1-microsoft-standard-WSL2 #1 SMP Thu Jan 11 04:09:03 UTC 2024 x86_64",
                "timestamp":    {
                        "time": "Thu, 18 Apr 2024 04:38:09 GMT",
                        "timesecs":     1713415089
                },
                "connecting_to":        {
                        "host": "127.0.0.1",
                        "port": 5201
                },
                "cookie":       "wtuhwwetnqayseccmqno6dutzjf3zly3op5p",
                "tcp_mss_default":      32768,
                "target_bitrate":       0,
                "fq_rate":      0,
                "sock_bufsize": 0,
                "sndbuf_actual":        16384,
                "rcvbuf_actual":        131072,
                "test_start":   {
                        "protocol":     "TCP",
                        "num_streams":  1,
                        "blksize":      131072,
                        "omit": 3,
                        "duration":     4,
                        "bytes":        0,
                        "blocks":       0,
                        "reverse":      0,
                        "tos":  0,
                        "target_bitrate":       0,
                        "bidir":        0,
                        "fqrate":       0,
                        "interval":     1
                }
        },
        "intervals":    [{
                        "streams":      [{
                                        "socket":       5,
                                        "start":        0,
                                        "end":  1.001066,
                                        "seconds":      1.0010659694671631,
                                        "bytes":        3578265600,
                                        "bits_per_second":      28595642717.968742,
                                        "retransmits":  0,
                                        "snd_cwnd":     2029973,
                                        "snd_wnd":      3145088,
                                        "rtt":  51,
                                        "rttvar":       5,
                                        "pmtu": 65535,
                                        "omitted":      true,
                                        "sender":       true
                                }],
                        "sum":  {
                                "start":        0,
                                "end":  1.001066,
                                "seconds":      1.0010659694671631,
                                "bytes":        3578265600,
                                "bits_per_second":      28595642717.968742,
                                "retransmits":  0,
                                "omitted":      true,
                                "sender":       true
                        }
                }, {
                        "streams":      [{
                                        "socket":       5,
                                        "start":        1.001066,
                                        "end":  2.001046,
                                        "seconds":      0.99997997283935547,
                                        "bytes":        3452698624,
                                        "bits_per_second":      27622142185.078888,
                                        "retransmits":  0,
                                        "snd_cwnd":     2029973,
                                        "snd_wnd":      3145088,
                                        "rtt":  88,
                                        "rttvar":       67,
                                        "pmtu": 65535,
                                        "omitted":      tr [...]

2025-05-23 03:12 UTC, manedurphy commented
Update (05/22/2025)

@bmah888 expressed concern over the value for the added `OPT_SERVER_MAX_DURATION`, as it is approaching a value close to those of other short-hand flags. The way I see it, these should be okay to increment as is up until ASCII `47`, as these values are unlikely to be used for flags. We can also increase it to `128` now and never think about it again. I'll leave that decision up to Bruce. My only concern left for the current implementation is the user-unfriendly message when the `iperf3` client's version is older. Is this a known limitation that users are familiar enough with to know what to do when then encounter the message `iperf3: error - int_errno=37: No locks available` which provides the error code from the server that the client does not have a case for? And if this is a well-known limitation and we can merge this change as is, is there room for an enhancement in the future? The way that I would approach this is for the client and server to exchange their respective versions, and when the server encounters an error for a feature that the client doesn't have awareness of, it will send a special code which indicates that the error has to do with a feature on a newer version of `iperf3`..... or something like that.

2025-06-01 12:07 UTC, davidBar-On commented on src/iperf_api.c
> +            case OPT_SERVER_MAX_DURATION:
`server_flag = 1;` should be added to this case.

2025-07-03 17:22 UTC, manedurphy commented on src/iperf_api.c
> +            case OPT_SERVER_MAX_DURATION:
Thanks @davidBar-On. I've added this.

2025-07-03 17:23 UTC, manedurphy commented
@bmah888 have you had some time to consider the approach we should take here given the constraints? @davidBar-On your input on this would also be appreciated.

It appears that it has always been an issue that an `iperf3` client could run into a case where it cannot provide more context for what happened on the server. Here is the output for a `3.8.1` client that is trying to exceed the duration of the `--server-max-duration` flag:

```
iperf3 -c 127.0.0.1 -t 10
Connecting to host 127.0.0.1, port 5201
iperf3: error -
```

So while a more sophisticated approach for providing more context to older versions of the client would be ideal, I'm not sure that it is absolutely necessary given the historical context. At least not necessary to move forward with this feature. An enhancement for this can be added to the code base separately.

2025-07-04 12:39 UTC, davidBar-On requested changes

2025-07-04 12:39 UTC, davidBar-On commented on src/iperf_client_api.c
> +            return -1;
Was this removal of leading spaces done by mistake?  Note that iperf3 indentation is 8 spaces.

2025-07-04 12:39 UTC, davidBar-On commented on src/iperf_error.c
> +            snprintf(errstr, len, "client's max duration exceeds the server's maximum permitted duration");
Suggest to replace "duration" with "test duration".

2025-07-04 12:39 UTC, davidBar-On commented on src/iperf_api.c
> +        {"server-max-duration", required_argument, NULL, OPT_SERVER_MAX_DURATION},
There is no need to add a new option, as `--time` can be used (the iperf3 team don't like new options).  Client will store the value in `duration` and server will store it in `max_server_duration`.  Note that when getting the `--time` value it should be stored in temporary variable, and only after all option values are received and it is known whether this is a server or client, it can be stored into the test structure.

This requires that the `--time` will become server and client feature, and the help message should state both the client and the server messages.  Note that

2025-07-04 17:33 UTC, manedurphy commented on src/iperf_client_api.c
> +            return -1;
Yes, this was a mistake. Thanks for catching that.

2025-07-04 17:33 UTC, manedurphy commented on src/iperf_error.c
> +            snprintf(errstr, len, "client's max duration exceeds the server's maximum permitted duration");
Changed

2025-07-04 17:48 UTC, manedurphy commented on src/iperf_api.c
> +        {"server-max-duration", required_argument, NULL, OPT_SERVER_MAX_DURATION},
The approach I've taken was to be consistent with [iperf/#999](https://github.com/esnet/iperf/pull/999), where the client's `--bitrate` flag and the server's `--server-bitrate-limit` flag are handled separately under different options even though they are both related to configuring bit rate. I'm in favor of maintaining consistency for the sake of the user's experience, but I also think that `--server-max-duration` makes it more clear that this flag has to do with test duration enforcement. We can even change it to `--server-max-test-duration` and `OPT_SERVER_MAX_TEST_DURATION` to be more consistent with the previous recommendation for changing `IEMAXSERVERDURATIONEXCEEDED` to `IEMAXSERVERTESTDURATIONEXCEEDED`. What do you think?

2025-07-04 18:12 UTC, davidBar-On commented on src/iperf_api.c
> +        {"server-max-duration", required_argument, NULL, OPT_SERVER_MAX_DURATION},
OK.  I agree a separate option is reasonable. I also think that `--server-max-duration` is good enough and there is no need to change it.

2025-07-11 19:04 UTC, bmah888 commented on src/iperf_api.c
> +        {"server-max-duration", required_argument, NULL, OPT_SERVER_MAX_DURATION},
I think adding a new flag is OK this case.

2025-07-11 19:15 UTC, bmah888 commented
> @bmah888 have you had some time to consider the approach we should take here given the constraints? @davidBar-On your input on this would also be appreciated.
> 
> It appears that it has always been an issue that an `iperf3` client could run into a case where it cannot provide more context for what happened on the server. Here is the output for a `3.8.1` client that is trying to exceed the duration of the `--server-max-duration` flag:
> 
> ```
> iperf3 -c 127.0.0.1 -t 10
> Connecting to host 127.0.0.1, port 5201
> iperf3: error -
> ```
> 
> So while a more sophisticated approach for providing more context to older versions of the client would be ideal, I'm not sure that it is absolutely necessary given the historical context. At least not necessary to move forward with this feature. An enhancement for this can be added to the code base separately.

I agree with you here...iperf3 wasn't designed to support perfect forward/backward compatibility between arbitrary versions of code. It was intended for deployments within a single administrative domain (or at least between cooperating administrative domains), where the requirements for compatibility are lessened a bit. In this case all we're missing is the ability to display a meaningful error message to the end-user on the client side.

2025-07-11 23:52 UTC, bmah888 commented
I've been testing this and it seems to be working as designed. 

One thing just occurred to me that if you run the server as `iperf3 --server --server-max-duration`, I can still force a really long test to run by doing something like `iperf3 --client iperf3.example.com --bytes 1T` or something like that (in other words, have my client specify a number of bytes or a number of blocks to transmit, both of which override the time duration). I'm not sure how to handle these cases, short of adding more limiting options.

2025-07-14 21:07 UTC, manedurphy commented
@bmah888 I'm open to adding those protections. I think having a flag per protection is fine since the goal is to give the administrator of the `iperf3` server more control over preventing a single client's ability to flood traffic. If I have a 10 Gbps server that is supposed to allow some pool of 30 devices to test their 1 Gbps speeds, then I can better ensure that no device is able to hog the server's bandwidth by:

1. Setting `--server-max-bitrate` to `1Gb/1s`.
2. Setting `--max-server-duration` to `15` since that's plenty of time to verify speed. The client can set `--omit 5` to account for TCP ramp up and `--time 10` for the test duration.
3. This would mean the theoretical max bytes transferred would be `1875000000 bytes`, to which I could set `--server-max-bytes` to protect the server from any device that wants to run a longer test. This would mean that devices with slower bit rates could run for longer than the configured `--server-max-duration`, but would never be able to exceed the maximum configured number of bytes that the server will accept via the `--server-max-bytes` flag.

For me, personally, as an `iperf3` server administrator, I care the most for my server's availability to meaningfully serve as many clients as possible, and preventing clients from dominating the server's resources. If someone wants to run a long `iperf3` client with `--bitrate 1Kb/1s --bytes 1875000000`, that's fine with me because it won't interfere with other devices.

I'd want to know if these additional changes should be implemented as part of these changes, or if I should raise them in a separate PR. I'm open to either, but tend to prefer raising separate PRs for separation of concern for the PR template.

2025-07-15 19:16 UTC, davidBar-On commented
> ... as an iperf3 server administrator, I care the most for my server's availability to meaningfully serve as many clients as possible, and preventing clients from dominating the server's resources.

I assume that means that the duration that a specific client is using the server is the most important limit.  In this case, instead of limiting bytes/blocks, at the beginning of the test the server can start a timer that will expire after the `--server-max-duration` and will allow the server to terminate the test.

Actually, the server already does something similar, in `create_server_timers()`.  Based on the test duration `test->duration + test->omit + grace_period`.  If that timer expires, `server_timer_proc()` is called and it terminates the test (I have submitted PR #1914 to enhance this function error handling).  The suggested approach is that when `--server-max-duration` is set, the timer will be set to the minimum between the parameter value and the value currently used for the timer.  Something like this:
```c
        max_duration = test->duration + test->omit + grace_period;
        if (test->max_server_duration > 0 && test->max_server_duration < max_duration) {
            max_duration = test->max_server_duration;
        }
        test->timer = tmr_create(&now, server_timer_proc, cd, max_duration * SEC_TO_US, 0);
```

2025-07-25 19:05 UTC, davidBar-On commented on src/iperf_api.c
> +
`errno` should also be sent to the client.  In this case `errno` is 0, so the following code should be added after sending `i_errno`:
```c
            err = 0;
            if (Nwrite(test->ctrl_sck, (char*) &err, sizeof(err), Ptcp) < 0) {
                i_errno = IECTRLWRITE;
                return -1;
            }
```

2025-08-15 17:51 UTC, bmah888 commented
> For me, personally, as an `iperf3` server administrator, I care the most for my server's availability to meaningfully serve as many clients as possible, and preventing clients from dominating the server's resources. If someone wants to run a long `iperf3` client with `--bitrate 1Kb/1s --bytes 1875000000`, that's fine with me because it won't interfere with other devices.

Thanks @manedurphy! Herein we're running into a difference in use cases between what iperf3 was originally designed for, and what people would (quite reasonably) like it to do. :-) iperf3 was originally designed to test between two specific hosts (i.e. client and server) at a time. In the networking environment it was designed for, it's very possible that the end hosts, rather than the network, are the bottlenecks to performance. So only one test per server process can be running at once (and ideally only one test per host at a time), to avoid interference between tests. There was also a general assumption that the client and server were loosely affiliated, or at least co-operating.

This is very different from people who want to run large-scale iperf3 speed-test type services that serve dozens or hundreds of potentially unknown clients, some of which might need some guardrails. I understand that the PR we're discussing is an attempt to adapt iperf3 to this use case, which is great. I'm just trying to poke (in a friendly way, or at least I'm trying!) at the solution to see what else might be needed to fit the requirements.

I appreciate wanting to support (server-side) limits on parameters as well, although I am not sure how these options should interact, particularly when the client side can only specify one of the ending criteria. So...my question back to you is do you think this PR is still useful as-is? I haven't quite made up my mind on this. (I see where @davidBar-On has some feedback also, which I haven't read yet.)

2025-08-22 03:50 UTC, manedurphy commented
@bmah888 I appreciate the additional context for `iperf3's` original design and use case. You are correct, this feature stems from a use case of large-scale speed testing. We have pools of `10Gb/s`, `40Gb/s`, and `100Gb/s` servers that are assigned to physical locations for serving `iperf3` clients that reside in those areas. We have 1 client process that interacts with 1 server process as `iperf3` was designed to do, but we cannot have only 1 server process per host due to our scale. Depending on the location, it can be either tens or hundreds of `iperf3` server processes on a single host, each of which interact with a single client process. I believe that this server-protecting feature falls in line with the `--server-bitrate-max` feature in [iperf/#999](https://github.com/esnet/iperf/pull/999), which I think has more usefulness when the client and server are not affiliated as does the proposed `--server-max-duration`.

@davidBar-On your proposed change of using the value of `--server-max-duration` to set the value of the timer actually falls more in line with the original implementation that @TheRealDJ and I discussed. However, I believe that the server should not allow the client to run at all when it can determine that it is destined to fail based on the client's input parameters. The same can be (conditionally) said for the `--server-bitrate-max` flag in the sense that if the server has this flag set to `1Gbit/1` and the client has `--bitrate` set to `2Gbit/1`, then the server should reject the test because it knows that it will exceed its configured maximum, and it should provide a message to the client which makes it clear why the test was rejected. In the cases where the server cannot determine this in advance, such as when the `--bitrate` in the client is not set, then the server should ideally send a user-friendly message to the client. As of now, there is a nice message on the server, `iperf3: error - total required bandwidth is larger than server limit`, but the client has no visibility into what went wrong, `iperf3: error - control socket has closed unexpectedly`. I believe the enhancement in [iperf/#1914](https://github.com/esnet/iperf/pull/1914) intends to do the same, where the server would print `iperf3: error - server test duration expired - test is terminated by the server`, but the client would still have no visibility into what went wrong. I'm bringing up the `--server-bitrate-max` here because I believe it's usefulness in protecting the server aligns with the purpose of the proposed `--server-duration-max`, and I believe that all server-protecting flags, current and future, should follow the same set of guidelines for implementation.

Guidelines:
- When the server has a protection flag set, like `--server-bitrate-limit`, `--server-max-duration`, or `--server-max-bytes`, etc, it should be prepared to evaluate and react to the client's respective input parameters: `--bitrate`, `--time`, `bytes`, etc.
- Should the server determine that the client's input parameters would effectively violate the protections it has set, then it should reject the test with a user-friendly message to the client which describes why the test was rejected: 
  - `client's requested bit rate exceeds the server's maximum permitted limit`
  - `client's requested duration exceeds the server's maximum permitted limit`
  - `client's requested bytes exceed the server's maximum permitted limit`
- Should the server not be able to determine by the client's parameters that the test will violate the server's protections, then the server should stop the test upon violation and send a user-friendly message to the client to explain why the test was stopped:
  - `client's bit rate exceeded the server's maximum permitted limit`
  - `client's bytes exceeded the server's maximum permitted limit`

Since it is always possible for the server to determine if the client's duration will violate it's protection, it will either reject or permit with success. For other protections such as bit rate or bytes, the server may not be able to determine if its protections will be violated, and will have to react accordingly.

2025-08-22 07:56 UTC, davidBar-On commented
@manedurphy, thanks for the detailed response.  In general, I fully agree with what you wrote.

> I believe that the server should not allow the client to run at all when it can determine that it is destined to fail based on the client's input parameters. The same can be (conditionally) said for the --server-bitrate-max flag ...

I agree that both checks should be done , both when receiving the client's parameters and during the test and that the parameters check should be added regarding `--server-bitrate-max`.

> ... then the server should ideally send a user-friendly message to the client. As of now, there is a nice message on the server, `iperf3: error - total required bandwidth is larger than server limit`, but the client has no visibility into what went wrong, `iperf3: error - control socket has closed unexpectedly` ...

I believe that I found a reasonable solution (actually a workaround) to this problem in PR #1909.  Once this PR (or a variant of it) will be merged, the client will (also) print the correct error message.  The idea is that if the server finds a problem with a parameter received from the client, it will send the error code as the next State to client (after making sure that no State and error code have the same value).  When the client receive the "State", instead of just printing `Received unknown state`, it suggests that maybe this is an error code and prints `Received unknown state <state code> from server, which may be the error: <the error string>`.

2025-08-25 01:04 UTC, manedurphy commented
@davidBar-On I was thinking of following the same pattern to convey the message. I've pasted a snippet below, but I'll open a new PR which has both the error handling and input validation for the sake of keeping this PR focused on handling the time parameter.

<details>

<summary>snippet</summary>

```c
// Check if average transfer rate was exceeded (condition set in the callback routines)
if (test->bitrate_limit_exceeded) {
    i_errno = IETOTALRATE;
    if (iperf_set_send_state(test, SERVER_ERROR) != 0) {
        cleanup_server(test);
        return -1;
    }

    err = htonl(i_errno);
    if (Nwrite(test->ctrl_sck, (char*) &err, sizeof(err), Ptcp) < 0) {
        cleanup_server(test);
        i_errno = IECTRLWRITE;
        return -1;
    }
    err = htonl(errno);
    if (Nwrite(test->ctrl_sck, (char*) &err, sizeof(err), Ptcp) < 0) {
        cleanup_server(test);
        i_errno = IECTRLWRITE;
        return -1;
    }

    cleanup_server(test);
    return -1;
}
```

</details>

My latest push here includes writing `errno` as per your requested change.

2025-10-03 17:22 UTC, bmah888 commented
@manedurphy thanks for your patience in dealing with feedback on this PR! I'm pretty happy with this in the state it's in, except there's a merge conflict with `master` caused by an unrelated PR. Would you be up for fixing that merge conflict on your branch? I can merge it then.

Also I noticed your PR #1931, you probably want that in as well before we do iperf-3.20, right?

2025-10-03 21:26 UTC, manedurphy commented
I think all of the PRs that were asked for `3.20` have already been merged, so this and #1931 can be merged whenever you feel they are ready. I've rebased both, but think I'll have to rebase again when one of them is merged.

2025-10-03 23:24 UTC, merged